# Header
menu:
  主页: /
  所有文章: /archives
  关于: /about

# SubNav
subnav:
  github: "https://github.com/lixuejiang"
  weibo: "http://weibo.com/p/1005051991745641"
  zhihu: "https://www.zhihu.com/people/li-xue-jiang"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: ''

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
google_analytics: ''
favicon: favicon.ico

#你的头像url
avatar: http://ggbond.qiniudn.com/%E9%A3%8E.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: xuejiangli
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  tboox: http://www.tboox.org/
  cllgeek: http://www.cllgeek.com/
  fangyi: http://fangyi.me/
  茅哥: https://greenmzc.github.io/
  小平: https://www.excaliburhan.com/
#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 金诚前端开发工程师
